### ISSUE TITLE
Abort on Parse Error

### ISSUE THREAD

**Issue by Knochenmarc** [anthonyftwang/minify-action#5]
My HTML generator produced some invalid code (silly me).  Consequently the minifier breaks as well with a Parse Error. BUT the action step gets flagged as success and not as failed.
In my workflow the next step deploys to gh-pages, which should not happen in that case. Well it did, even worse: the affected file is just empty. So I've automatically deployed an empty html-file.

I think the exit code of minify gets not forwarded through the container. So the action doesn't know that it should fail.

Shorted Log of Minify-Step:

```
(Reading database ... 29947 files and directories currently installed.)
Preparing to unpack .../libio-pty-perl_1%3a1.08-1.1+b2_amd64.deb ...
Unpacking libio-pty-perl (1:1.08-1.1+b2) ...
Selecting previously unselected package libipc-run-perl.
Preparing to unpack .../libipc-run-perl_0.94-1+deb9u1_all.deb ...
Unpacking libipc-run-perl (0.94-1+deb9u1) ...
Selecting previously unselected package moreutils.
Preparing to unpack .../moreutils_0.60-1_amd64.deb ...
Unpacking moreutils (0.60-1) ...
Setting up libio-pty-perl (1:1.08-1.1+b2) ...
Setting up libipc-run-perl (0.94-1+deb9u1) ...
Setting up moreutils (0.60-1) ...
Error: Parse Error: <a  href="https://example.com"
                                    title="new cool book: "Hello World", by somebody">
... [some more html] ...
</body>
</html>
    at new HTMLParser (/usr/local/lib/node_modules/minify/node_modules/html-minifier-terser/src/htmlparser.js:244:13)
    at minify (/usr/local/lib/node_modules/minify/node_modules/html-minifier-terser/src/htmlminifier.js:993:3)
    at Object.exports.minify (/usr/local/lib/node_modules/minify/node_modules/html-minifier-terser/src/htmlminifier.js:1354:16)
    at AsyncFunction.module.exports [as html] (/usr/local/lib/node_modules/minify/lib/html.js:45:21)
    at onDataRead (/usr/local/lib/node_modules/minify/lib/minify.js:75:44)
    at optimize (/usr/local/lib/node_modules/minify/lib/minify.js:61:18)
    at async minify (/usr/local/lib/node_modules/minify/lib/minify.js:35:12)
    at async Promise.all (index 0)
```

**Comment by anthonywangcl** [comment]
Closing as stale (3+ years). The underlying minify package behavior may have changed with recent updates. If this is still an issue, feel free to open a new issue with details.
