### ISSUE TITLE
No possibility for diclining not to compress automatically the node_module's js

### ISSUE THREAD

**Issue by vajda-media** [anthonyftwang/minify-action#6]
Hi team, it would be nice to have an option of declining certain js of minifyings. Seem like it runs through the node_modules files and trying there as well to compress everything.

Action Output:

Unpacking moreutils (0.60-1) ...
Setting up libio-pty-perl (1:1.08-1.1+b2) ...
Setting up libipc-run-perl (0.94-1+deb9u1) ...
Setting up moreutils (0.60-1) ...
JS_Parse_Error [SyntaxError]: Unexpected token: operator (<)
    at js_error (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:554:11)
    at croak (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:1278:9)
    at token_error (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:1286:9)
    at unexpected (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:1292:9)
    at expr_atom (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:2558:9)
    at maybe_unary (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:3375:19)
    at expr_ops (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:3426:24)
    at maybe_conditional (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:3431:20)
    at maybe_assign (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:3508:20)
    at expression (/usr/local/lib/node_modules/minify/node_modules/terser/dist/bundle.min.js:3533:24) {
  filename: '0',
  line: 31,
  col: 17,
  pos: 1453
}

**Comment by anthonywangcl** [comment]
Closing as stale (2+ years). If you still need this feature, feel free to open a new issue or PR!
